### ISSUE TITLE
Restructuring the documentation

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#108]
The current documentation sections "Getting Started" and "Usage" are not as useful or easy-to-understand as they should be.

Here is a suggestion for a new structure:

0. Remove "Installation" as own page
1. Change "Getting started" to have the following sections:
   - Installation: what previously was on the "Installation" page
   - Project-specific configuration: explain that each project has a configuration folder usually hosted on Github, explain that a user has to download/clone the GitHub repo to run the validation for a specific project locally
   - Data validation: One paragraph showing the CLI for `nomenclature validate-project .`
2. Change "Usage" to have the following *sub-pages*
   - Folder structure
   - Definitions
   - Mappings for region processing

The Usage pages should be aimed at novice Python users, so avoiding Python jargon. Also, "Notes" is probably not an idea header, because it does not tell a user what kind of notes to expect... Better to have descriptive sub-section titles.

**Comment by danielhuppmann** [comment]
What do you think, @phackstock?

**Comment by phackstock** [comment]
Thank you for the proposed outline @danielhuppmann, agree with all of the above. That structure makes a lot more sense.
