### ISSUE TITLE
Single constituent common region can lead to unexpected results

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#116]
This is the result from a conversation with @pweigmann.
The partial region aggregation feature can lead to unexpected results if it is only comprised of a single common region, e.g.:

```yaml
model: model_a
common_regions:
  - Region_A:
    - region_a
```

this configuration is not super rare as it can often be the case that a region, that a model natively reports, `region_a` in the example, falls under the category of a comparison region. In this case, no aggregation is necessary, a renaming from `region_a` to `Region_A` is sufficient to ensure comparability with other models.

This is where unexpected behavior can occur as `common_regions` in essence means "perform region-aggregation". At the same time, region aggregation works on a principle we call "partial region-aggregation" (https://nomenclature-iamc.readthedocs.io/en/latest/usage.html#partial-region-aggregation) which means that nomenclature will perform the aggregation of the constituent regions but only use that for comparison. The results of the processing will be the model native results. 
However, this only works if the name of the **resulting** common region, in our case `Region_A` remains the same, i.e.:

```yaml
model: model_a
common_regions:
  - Region_A:
    - Region_A
```
if we have a renaming only the aggregated results will be used. 
This is normally not a problem as they _should_ be identical to the provided model native values. 
However, in a variable uses weighted aggregation such as `Price|Carbon` and the weight variable contains negative values we lose data points where the weight is negative.

There are a few options that this problem can be fixed/circumvented:
1. Disallow single constituent common regions, instead force them to be in the `native_regions` section.
2. Implement a check in the region aggregation to skip aggregation in case a common region is only comprised of a single region and only rename.

My preference would be option 1. as it is cleaner to implement, the region aggregation comparison feature does not really make sense if the region is only comprised of a single region, and there is another related issue with the current implementation:

Assuming a model natively reports two regions, "region_a" and "region_b". Assuming further that they should both be renamed to "Region_A" and "Region_B" respectively. Minus the potential issues with missing data, the following model mapping works:
```yaml
model: model_a
native_regions:
  - region_a: Region_A
common_regions:
  - Region_B:
    - region_b 
```
The inconsistency here is that for `native_regions` the value on the **right** is the one that will be in the result, For `common_regions` (here used for renaming only), on the other hand, the one on the **left/above** is the desired one. 
One way to solve this would be go with option 1. mentioned above and disallow single-constituent common regions. This would also be in line with the [zen of python](https://peps.python.org/pep-0020/) "There should be one-- and preferably only one --obvious way to do it.". In this case the renaming of model native regions could be done **only** by adding it to the `native_regions` list. 
If we go with this option we might also have to reconsider the naming of the two categories `native_regions` and `common_regions` as they would then more closely correspond to `do-not-aggreate` and `aggregate`.

@danielhuppmann, please let me know what you think.
Also @pweigmann, @orichters and @Renato-Rodrigues (you guys came to mind first as modellers that have current experience with using nomenclature, please feel free to loop in other colleages), your input is most welcome.

**Comment by danielhuppmann** [comment]
If I understand this correctly, this is not actually a bug but rather potentially unintuitive behavior. It is true that the highly generic example above is confusing, i.e.,

```yaml
model: model_a
native_regions:
  - region_a: Region_A
common_regions:
  - Region_B:
    - region_b 
 ```

but in an actual project setting, this would like as follows:

```yaml
model: model_a
native_regions:
  - EUR: model_a|EUR
common_regions:
  - Europe:
    - EUR
 ```

In my opinion, this is not a major reason for concern, but rather highlights that we need to improve our documentation, not change the logic of the processing.

**Comment by phackstock** [comment]
I partially agree, for sure the documentation needs to be better, I'll make sure I get on that right away.

There are, however, in my opinion two issues that go beyond that: 

1. Potential for data loss: If the `common_region` in question is renamed as is your example `- Europe: EUR`, the resulting data will be obtained through region processing alone. Not only is this unnecessary work, making the processing slower, as you could just use the provided data, it can also lead to data loss in case the aggregation fails. 
We had this issue in ngfs-internal recently where a variable `Price|Carbon` that had a weighted aggregation (using `Emissions|Kyoto Gases`) had a negative weight after the year 2060. As is the pyam default, the negative values were dropped. This lead to missing values in `Price|Carbon` even though the complete `Price|Carbon` timeseries was provided model natively. 
This could be mitigated[^1], by skipping region aggregation and simply taking the provided model native results in case a `common_region` just consists of a single region. 
2. Inconsistency with the renaming: I frequently find myself going over the question "What is region x now going to be uploaded as?". For `native_regions` it is the 'upload name' is the second value (taking your previous example: `- EUR: model_a|EUR`), while for `common_regions` it is the first one (- `Europe: EUR`). Maybe it's just me but I find that a bit inconsistent and as a result confusing. 

[^1]: In the specific case of ngfs-internal it was solved by choosing a different aggregation weight, that did not have negative values.

**Comment by danielhuppmann** [comment]
As a suggestion for 1, we could split out common-region mappings that only have one component and treat them via renaming.

For 2, I still believe that a clear separation into common regions (used for comparison in a project) vs. native region is the more intuitive approach for modelers. The alternative (assuming you would want to save the native region and the compare-region) would be to have 
```yaml
model: model_a
native_regions:
  - EUR: model_a|EUR
  - EUR: Europe
```
which will be just as confusing for larger models...

**Comment by phackstock** [comment]
Both proposed points sound good to me, let's do it that way.
