### ISSUE TITLE
Navbar in docs does not expand enough

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#138]
## Problem outline
In the [docs](https://nomenclature-iamc.readthedocs.io/en/stable/) the navbar on the left side does not expand deep enough when navigating to a section.

## Example

![image](https://user-images.githubusercontent.com/20710924/180721271-bfbda04c-0869-4e3f-8ae3-0cba6439db2f.png)

In the example we're in the section `Validaiton using Codelists`. For convenience, the navbar on the left should expand to contain the items: `Codelist format specification`, `Variable`, etc... 

## Proposed fix

Should be easy to adjust the maximum level of depth that the navbar expands to.

**Comment by danielhuppmann** [comment]
Ok, I'm taking a look at fixing the tac-depth and restructuring the user guide...

**Comment by phackstock** [comment]
Perfect, thank you.
