### ISSUE TITLE
Add validation-CLI option to check 'all' dimensions

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#157]
Building on #147.

We have several projects where we also use the "scenario" dimension for validation, eg https://github.com/iiasa/ariadne-intern-workflow, and we sometimes run into the problem that PRs that change the scenarios-codelist do not trigger the validation but then fail in production (ie when users upload a scenario data file).

We could now change the GitHub Actions workflow in that repository to

```
      run: nomenclature validate-project . --dimensions "['variable', 'region', 'scenario']"
```

However, this would still require a project manager to be aware that this change is necessary when adding validation for new dimensions.

I think it would be better to have a generic option, e.g., 

```
      run: nomenclature validate-project . --dimensions all
```
where all folders in *definitions* are checked automatically.

The GitHub Actions workflow in the template repository https://github.com/iiasa/scenario-explorer-workflow-template should then also be updated accordingly, so that by default, all dimensions are checked in all new projects.

**Comment by luciecastella** [comment]
Would 
<run: nomenclature validate-project . --dimensions "['all']">
Also work? It really is not really pretty, but I do not think I can change the class for dimensions and it currently needs a literal value. Otherwise, we could think about another option? Something like <--all_dimensions> ?

**Comment by phackstock** [comment]
I would say the question is more _should_ it work, i.e. should giving a list of dimensions which includes "all" evaluate everything. 
From looking at it quickly I would say that something like:
```console
nomenclature validate-project . --dimensions all
```
should work since the `ast.literal_eval(value)` should convert it to a single string. If you want I can take this issue.

**Comment by danielhuppmann** [comment]
Simply expanding the selection to 
```python
            if value == "all":
                return value
            return ast.literal_eval(value)
```
seems to work, at least for passing the right string to the following function.

What you'd need to add in the cli (or maybe even in `testing.assert_valid_structure()`?) that the code checks which folders exist in *path*...

**Comment by danielhuppmann** [comment]
Thinking one step further, it might even make sense to simply switch the default behavior of `testing.assert_valid_structure()` to use "all"? So that we don't even have to change any of the tests in GitHub Actions workflows (but have the option to make tests less strict by explicitly specifying which dimensions to check).

**Comment by phackstock** [comment]
@danielhuppmann yes good point, that should be the best option. 
Unless dimensions are specified, evaluate all. 
That would mean updating the default value of the cli and of `testing.assert_valid_structure()`. This way we could also leave the `dimensions` attribute to be `List[str]` only instead of `Union[List[str], str]`.

**Comment by luciecastella** [comment]
Great ideas thank you! Yes good point with the default behavior. So no need for the command line?
@phackstock I can try to figure it out and I'll tell you if you need to take over, OK for you?

**Comment by phackstock** [comment]
@luciecastella sounds good. You can see how far you get and if you get stuck just open a draft PR and I can take over then.

**Comment by danielhuppmann** [comment]
Right, to clarify the agreement:
- the CLI uses `None` as default but allows to accepts a list (using `ast.literal_eval()` if a value is given)
- the testing function uses `None` as default -> reading all folders in `definitions`, or accepts a list of dimensions explicitly.

**Comment by danielhuppmann** [comment]
So there is no need to bother with a string "all", but the docstrings should specify the (new) behavior clearly.

**Comment by phackstock** [comment]
@danielhuppmann yes to all of the above. That looks like a really clean way to me.
