### ISSUE TITLE
Variable and Region definition not mandatory anymore

### ISSUE THREAD

**Issue by luciecastella** [IAMconsortium/nomenclature#165]
I realised that now that the program checks for all the dimensions to be found when nothing is specified, it will just validate the ones it founds. Meaning we could totally have just a scenario folder with no variable and region definition and it would pass the validation. This was not the case before as they were in the default value. Should we change that and require variables and regions when nothing is specified?

**Comment by danielhuppmann** [comment]
I think that this behavior is fine. But following up on our discussion, it would be useful to raise an error if no sub-folders exist in `definitions`.
