### ISSUE TITLE
New release v0.6

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#175]
Just fixed a little bug in #171 for @willu47 and @HauHe, see https://github.com/OSeMOSYS/osemosys2iamc/pull/23#issuecomment-1231734834 - could you please make a new release v0.6 asap so that they can continue their work on the **osemosys2iamc** package?

**Comment by phackstock** [comment]
Sure, no problem, if it's only minor changes, should we go for v0.5.1 or v0.6?

**Comment by danielhuppmann** [comment]
I wouldn't make life too complicated and just go for v0.6.

**Comment by phackstock** [comment]
Alright will do

**Comment by phackstock** [comment]
We are live with v0.6 https://pypi.org/project/nomenclature-iamc/.

**Comment by danielhuppmann** [comment]
Thank you very much!
