### ISSUE TITLE
Attribute access

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#189]
One potential pitfall that I stumbled upon when finalizing #186 and then #188 was the breaking change that we are about to introduce with regards to attribute access.

The main update that we are about to introduce is that now a `CodeList` contains a list of `Code` instances. To be more precise it is not a list of `Code` instances but actually a dictionary mapping the name of the `Code` to the its instance. This is to facilitate the lookups we needed during e.g. region aggregation.

This has the potential for some inconsistency and breaking changes though. Taking an example from development, one of the tests had to be changed from: 

```python 
assert region["Norway"]["eu_member"] is False
assert region["Norway"]["iso2"] == "NO"
```

to: 

```python 
assert region["Norway"].attributes["eu_member"] is False
assert region["Norway"].attributes["iso2"] == "NO"
```
This is to accommodate the flexible nature of codelists where arbitrary attributes can be set.

One simple change in the `Code` class would be to implement a `__getitem__` method for accessing the attributes directly without having to go through `Code.attributes`. This way `region["Norway"]["eu_member"]` would still work.

This would, however, create some inconsistency as `VariableCode(Code)` has fixed attributes for region aggregation (unit, weight, method, etc...). These are simply accessed by `VariableCode.unit`. This means that in order to access an attribute a user would need to know if the attribute in question is a predefined one or an arbitrary one. 

An alternative to the `__getitem__` option (my preferred way) would be to implement `__getattr__` allowing "attribute type" access. Getting the `eu_member` status of Norway would then be `region["Norway"].eu_member`. The downside to this would be that we would need to restrict the keys used in the codelists to valid python attributes (no leading numbers, whitespace, dashes, etc...). That should be easy to check though and in my opinion still the be way to go.
An additional side benefit would be that even for the `Code` class there are currently two fixed attributes `name` and `description`. Using `__getattr__` would also make `Code` consistent.

As these are potentially breaking changes I would hold off from merging #188 for now and implement them there once we are certain about which way we want to go.

Would love to hear your thoughts @danielhuppmann.

**Comment by danielhuppmann** [comment]
When in doubt, do what pandas does... 😜 And pandas actually supports both `df.column` and `df["column]` for a column!

But that's probably overkill, so I agree with you that the attribute-access is more intuitive and faster to work with.

**Comment by phackstock** [comment]
Ah right, of course pandas allows for both. I don't think doing both will cost that much more implementation time so I'll try to do both.

**Comment by danielhuppmann** [comment]
Actually, I rescind my earlier comment - let's not do both, because there is no real benefit and only possible confusion.

I guess pandas only does it for legacy reasons or to allow access if the column.name shadows a proper attribute.

Let's do attribute-access-only here...

**Comment by phackstock** [comment]
Ok sounds good as well. I'll implement that as part of #188.
