### ISSUE TITLE
Remove no longer needed validation schema for VariableCode

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#192]
Now that the attributes of `VariableCode` are fixed in the class the validation schema is no longer needed.

**Comment by danielhuppmann** [comment]
I guess that we can remove the json-schema validation entirely? We should need to validate that the yaml files are correctly parseable - all other validation (correct structure, etc.) could be moved to pydantic... But we should probably do this step by step.

**Comment by phackstock** [comment]
Getting rid of the json-schema crutch entirely is very much the goal. The two places where I think we need it right now is for the regions and the tags. But of course that is nothing that cannot be addressed in the code directly. For now though I'd keep it to just removing the variable-schema.
