### ISSUE TITLE
Region-Mapping for scenario explorer workflows

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#20]
Opening the issue per discussion with @danielhuppmann. 

We want a function which can do region aggregation given two inputs: `df: IamDataFrame` and `mapping_path: pathlib.Path`. It should return the aggregated `IamDataFrame`.

Some open points: 

* Should the returned dataframe **only** contain the aggregated regions or also the original constituent regions?
* Should the function make use of the region aggregation capabilities of [`IamDataFrame.rename()`](https://github.com/IAMconsortium/pyam/blob/5f10925022f90f2b6b2ecbef14e935b38e3852a2/pyam/core.py#L1003) or [IamDataFrame.aggregate_region()](https://github.com/IAMconsortium/pyam/blob/5f10925022f90f2b6b2ecbef14e935b38e3852a2/pyam/core.py#L1328)
* How do we preform region aggregation for variables where a simple sum is not the correct way to aggregate?

**Comment by stefanpauliuk** [comment]
>     Should the function make use of the region aggregation capabilities of IamDataFrame.rename() or IamDataFrame.aggregate_region()

The common way of aggregating data (assume data are in some multi-index table format) is a matrix multiplication:
Agg_Data = Agg_Matrix.dot(Full_Data)
The 'old' classification disappears and the new classification is returned.
Therefore, I prefer to only return data for the new (target) set of regions.

> How do we preform region aggregation for variables where a simple sum is not the correct way to aggregate?

for an n:1 aggregation, the Agg_Matrix can be condensed as list: which old position is added to which new position, and the method builds the Agg_Matrix with 1 at the relevant positions.
for an n:m aggregation, one option would to actually supply the aggregation matrix, containing fractions, could be supplied directly or constructed from a dictionary with the structure { Old_region: [New_region, Fraction]}

**Comment by danielhuppmann** [comment]
Thanks @stefanpauliuk for chiming in. Your answer is correct in a matrix sense, but pyam uses a different data format internally - and the question was intended about which of the existing pyam methods to use.

About the "not just simple sum", this was meant about things like a weighted average, not splitting model-native regions across compare-regions. This would be an interesting use case, but is currently not supported by pyam, and would probably require some more thought to implement correctly.

[For example: how would "take 50% of region A" work in a emissions-weighted carbon price aggregation? But this is not a discussion for here, but should be a feature-request discussion in the pyam repository.]

**Comment by phackstock** [comment]
Now that I'm getting around to implement this feature two design questions came up:

1. What happens if we there is no mapping defined for a given model? Do we just not do anything and pass the IamDataFrame untouched, write a warning, or even throw an error? Alternatively we could also require a model mapping but allow that to be empty, i.e. just a `model` parameter and nothing else. 
2. Let's say we have a model which has regions `region_a` and `region_b` and the following model mapping:
    ```yaml
    model: model_1
    native_regions:
      - region_a: region_A
    common_regions:
      - World:
        - region_a
        - region_b
    ```
How do we handle `region_b`? Do we just upload it as is or do we say that **if** a model mapping is defined all the native_regions that should be uploaded need to be mentioned. Going that route would be a little bit more verbose but it would allow for implicit exclusion lists (although maybe we should add explicit ones as whole new feature) and it would make it easier to see what kind of native regions a model is reporting.

Would love to hear your thoughts @danielhuppmann.

**Comment by danielhuppmann** [comment]
Good questions @phackstock:
1. Yes, if no mapping is defined for a model, then the IamDataFrame is returned untouched by the region-processor. I would not write a warning - instead write an info to the log "Applying region mapping for model {model}".

2. I'd say that if an entry `native_regions` exists in the config, then only the renamed native-regions and the aggregated common-regions (if any) are included in the returned IamDataFrame.

And the following should also be allowed:
```yaml
model: model_1
native_regions:
common_regions:
  - World:
    - region_a
    - region_b
```
This would compute the aggregated "World" region and throw away the data for "region_a" and "region_b". (This would require a little modification of the codebase to allow null as arg to the dictonary in addition to a list of dictionaries.)

**Comment by phackstock** [comment]
Ad 1. Perfect, I'll implement it that way.
Ad 2. In keeping with the zen of python 'explicit is better than implicit' I would propose an additional, optional attribute in the mapping called `all_native_regions` or `upload_all_native_regions` or something along those lines. We could say that either simply adding this would upload all native regions or we could require `all_native_regions: True`.

**Comment by danielhuppmann** [comment]
To limit the scope of the ongoing development, I'd keep the option of a "direct pipeline" as a feature request for the future for now, because I expect a number of tricky corner cases.

So (changing what I said a while ago), if a mapping exists, the RegionProcessor returns only the (possibly renamed) native-regions and the computed common-regions.

**Comment by phackstock** [comment]
Ok sounds good.
