### ISSUE TITLE
VariableCode ValidationError when generating variable template

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/nomenclature#217]
Trying to edit/add to the `engage_internal` variable template, but info that is already there, regarding the `Region_aggregation` and `Weight` is causing an issue e.g. Documented here in https://github.com/iiasa/engage-internal-workflow/pull/62

Removing both of those two columns resolves the issue.

Files included in the PR should recreate the issue. @danielhuppmann had a try already but says is issue in nomenclature for more complex attributes

https://github.com/iiasa/engage-internal-workflow/blob/5e76f80be4e4bef402721080322e450871560c69/definitions/Tutorial_edit_existing_variable_codelist.ipynb

N.B the excel file included in the above PR, already has the edits / additional variables that I would like to include. But they are not what are causing the issue (e.g. the Region agg and weight info for `Price|Carbon` was already there)

**Comment by phackstock** [comment]
Thanks for opening the issue. I'll take a look at it.

**Comment by phackstock** [comment]
I'll open two new separate issues and create the corresponding fixes.

**Comment by phackstock** [comment]
Addressed in #218.
