### ISSUE TITLE
RegionProcessor.apply drops meta data

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#227]
As discovered when working on the GENIE project, the `RegionProcessor.apply` currently removes all original meta indicators.
FYI @danielhuppmann

**Comment by danielhuppmann** [comment]
This is strange... Just had a quick look at the code, it looks like the RegionProcessor only uses methods that preserve the meta indicators: `filter`, `aggregate_region`, `append`, `concat`...

**Comment by phackstock** [comment]
Maybe we've encountered a special case here, in the workflow in question we did not keep any native regions and instead only aggregated. Perhaps that has something to do with it.
