### ISSUE TITLE
Default-attributes are exported to yaml

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#231]
When initializing a `VariableCode`, the attributes `region-aggregation` and `skip-region-aggregation` are automatically added and set to "False". When then exporting the CodeList to yaml, these attributes are written explicitly to the file, leading to very cumbersome, unwieldy files, see for example https://github.com/iiasa/ariadne-intern-workflow/pull/42

This is implemented in this line (and following)

https://github.com/IAMconsortium/nomenclature/blob/0b3dec191879faead7c0071d67a6d2bc5cb3035b/nomenclature/code.py#L142

I see two options:
1. don't automatically add these fields to the `VariableCode` if they are not defined in the source yaml/xlsx file
2. remove these attributes (if `False`) when exporting to yaml

**Comment by phackstock** [comment]
Thanks for opening this issue @danielhuppmann. I am aware of this issue and would strongly suggest option 2. 
Reason being that it's easier and more logical to work with the values actually set to true or false. I think using none could be ambiguous. 
The reason why I didn't fix it in the past was that I didn't find a quick way to check with pydantic if the value that a field has is the default value. But I'm sure there's a way.

**Comment by phackstock** [comment]
Took a quick look at the pydantic docs (https://docs.pydantic.dev/usage/models/#model-properties) and found a solution in form of the `__fields_set__` attribute. It does everything we need.
