### ISSUE TITLE
nomenclature install from GitHub fails exclude tests

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#275]
When installing nomenclature from GitHub, the tests break as of #272. 
This is expected since the `nomenclature` `pyam` dependency refers to pypi and not GitHub. 
The only reason that the tests in #272 ran is that we explicitly pre-install GitHub pyam before installing the rest of the dependencies, see https://github.com/IAMconsortium/nomenclature/blob/981dedc148ad57c97d32bb687ee4d238a7a3bdd3/.github/workflows/pytest.yml#L33-L37

I would propose two things: 
1. Set the nomenclature pyam dependency from pypi to GitHub, at least until there's a newer pyam release.
2. Remove the above mentioned GitHub installation as part of the test since this can lead to unexpected outcomes.

**Comment by danielhuppmann** [comment]
We'll do a new release following the release of pyam 2.0 - it's a matter of a few weeks at most.
