### ISSUE TITLE
country names

### ISSUE THREAD

**Issue by danhooke** [IAMconsortium/nomenclature#287]
Hi, we have noticed inconsistencies between the pycountry "name"(https://github.com/flyingcircusio/pycountry/blob/main/src/pycountry/databases/iso3166-1.json) and the official ISO 3166 country names (https://www.iso.org/obp/ui/#search), so far for "Turkey/Türkiye", "United States/United States of America". One solution would be to override these in countries.py, as done for Bolivia etc. I can do this if it is your preferred solution?

**Comment by danielhuppmann** [comment]
Thanks for noticing. My preference would be to stick with pycountry conventions, in the interest of readability and short names.

**Comment by danhooke** [comment]
ok sounds good, we will override the country names on our end of things then
