### ISSUE TITLE
Allow wildcard variables

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#294]
Per a discussion with @volker-krey and @phackstock:

Previous projects added a "counter" to capacity- and capital-cost variables to allow reporting of different types of plants, e.g., "Capacity|Electricity|Biomass|1", with a mapping of the number to a particular type given in a comments sheet.

This is a not very elegant approach and not user-friendly when viewing the data via the Scenario Explorer.

It would be preferable to explicitly allow wildcards in a variable name, e.g., `Capacity|Electricity|Biomass|*` - and the nomenclature-validation would allow all variables starting with *Capacity|Electricity|Biomass*. This way, each modelling team could define the types individually, using either numbering or more useful description like "CCGT" directly in the variable name.

**Comment by phackstock** [comment]
I see the application but I'm a little bit worried that this defeats the purpose of having a _defined_ variable list in the first place. If it's all custom to the model should it be part of a comparison study anyway?
