### ISSUE TITLE
Add NUTS regions as an option

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#343]
I think this could be a very nice first task for @dc-almeida. Adding NUTS regions as part of nomenclature.yaml
What do you think @danielhuppmann?

**Comment by danielhuppmann** [comment]
Agree, @phackstock...

The current official list of NUTS regions is available at https://ec.europa.eu/eurostat/web/nuts/overview

In the **openENTRANCE** project, I developed a prototype here: https://github.com/openENTRANCE/openentrance/blob/main/definitions/region/nuts3.yaml, where three files (one for each NUTS-level) where generated from the NUTS definitions file (2021 version).

For a new version, I think it's easier to parse the xlsx file when initializing a **DataStructureDefinition** with something like
```yaml
definitions:
  region:
    country: true
    nuts: [1, 2, 3]
```
and add the **RegionCode** items to the **RegionCodeList**.
