### ISSUE TITLE
Add CLI option to run workflow file from command line 

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#351]
For a lot of local upload trouble shooting it would be nice to run something along the lines of:

```console
nomenclature run_workflow input_data.xlsx
```
 
`run_workflow` would default to importing `workflow.py` from the current working directory and run the function `main` from `workflow.py`

**Comment by danielhuppmann** [comment]
very nice idea!

**Comment by phackstock** [comment]
It's pretty much required for the new data template building workflow since projects have varying dimensions and we need a way to specify what to build.

**Comment by danielhuppmann** [comment]
Maybe add this spec to `nomenclature.yaml`? Then workflow.py and the export-project CLI can import from there?

**Comment by phackstock** [comment]
I would've added it to the build specifications but `nomenclature.yaml` also makes sense. That could also be used in the list of dimensions we want to validate.
However, then we'd have to add a `nomenclature.yaml` in every workflow repo even if we don't use anything else in `nomenclature.yaml`

**Comment by danielhuppmann** [comment]
For what it's worth, I think that #353 does not really close the initial idea for this issue

**Comment by phackstock** [comment]
Ah sorry for that, I thought we had a separate issue on specifying dimensions... too much multi tasking ...
