### ISSUE TITLE
Model registration template does not contain the "ISO3" code for Kosovo

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#376]
Might be good to check the whole list if there's any other inconsistencies.

**Comment by danielhuppmann** [comment]
Good point, but should be ok because I only added that manually. But if we clean that up, we might also want to defined an ISO2-code for Kosovo for completeness?

**Comment by phackstock** [comment]
Sure, we can also come up with an ISO2, no objections from my side there.

**Comment by danielhuppmann** [comment]
https://en.wikipedia.org/wiki/XK_(user_assigned_code) to the rescue
