### ISSUE TITLE
Region processing: skip variable

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#40]
When refactoring the https://github.com/openENTRANCE/nomenclature to work with this new package, I realized that it would be helpful to have a "skip"-option for variables in a DataStructureDefinition.

Options:

1.
```yaml
Complicated Variable:
 - region-processor: skip
```
2.
```yaml
Complicated Variable:
 - skip-region-processing: true
```

Or maybe use "exclude" instead of skip?

Any thoughts @phackstock @peterkolp?

**Comment by phackstock** [comment]
Just to avoid confusion by skipping you mean that it would not be returned as part of `RegionProcessor.apply(df)` right?
Do we need an explicit skip option, would it not work if we just leave it out?
If we need it I would vote for option 2 for two reasons. Using `skip-region-processing` is more descriptive in my opinion and a boolean is easier to validate/assert/parse.

**Comment by danielhuppmann** [comment]
For clarification: there could be a variable which we want to include in the native regions as part of an upload (so the variable has to be in the `DataStructureDefiniton` for validation), but where pyam does not (yet) support the correct regional aggregation - so we want to exclude it from `RegionProcessor.apply()`.

**Comment by phackstock** [comment]
Ah ok so maybe `skip-region-aggregation` or `do-not-aggregate` would be more precise?

**Comment by danielhuppmann** [comment]
Preference for `skip-region-aggregation`...

**Comment by phackstock** [comment]
Sounds good.
