### ISSUE TITLE
Make "tier" a known attribute as integer

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#409]
We often use `tier` as a variable-attribute to indicate importance of a variable - tier 1 is mandatory to be reported in a scenario-comparison project, tier 2 and 3 are optional.

This could be added as a standard attribute (as integer) to the VariableCode, but with a tag-list twist (a very special case of #402).

- If the Variable has a tier and the tag-list doesn't: easy
- If the Variable has a tier and the tag-list has a tier-attribute of the type "+1" - add the value to the tier.
- If the Variable doesn't have a tier: ignore

[I suggest the format "+1" to clearly indicate that this is added. If the tier in a tag-list is an integer, an error should be raised.]

This would help in cases like [here](https://github.com/IAMconsortium/common-definitions/blob/main/definitions/variable/energy/final-energy.yaml#L26) where `Final Energy|Non-Energy Use|Chemicals|Liquids` should have tier 2 but `Final Energy|Non-Energy Use|Chemicals|High Value Chemicals|Liquids|Biomass` should probably be tier 4. The of these variables are made of the same tag-lists (each combining different priorities), so having this flexibility to indicate priority within a tag list would be very helpful...

**Comment by dc-almeida** [comment]
This could then have a cumulative effect, right? A variable with multiple tags with a tier modifier would increment the value that many times. C/Would this be used for numbers other than +1 and negative numbers?
