### ISSUE TITLE
Add Logging to region processing

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#42]
As of right now there is no logging happening in the context of region processing.
This should be changed prior to the first release.

**Comment by danielhuppmann** [comment]
Thanks for opening this issue. I'd go for very short logging, one line per "model" in the IamDataFrame instance:
 - if no mapping file exists: "No region aggregation mapping found for model {model}"
 - else: "Applying region aggregation mapping for model {model} from file {file}"

**Comment by phackstock** [comment]
That should be on the info level right?
Should we log errors as well?

**Comment by phackstock** [comment]
Ah alright, I'll keep it to info then.
