### ISSUE TITLE
Add warning-feature to DataValidator

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#426]
As a next step for scenario validation and vetting, we need to extend the **DataValidator** class to enable showing a warning instead of raising an error.

My proposed implementation is the following:
- Add a **warning-level** attribute to a validation-criteria item, which defaults to None, but can be set to e.g. "red", "yellow"
- This will probably require an intermediate class **DataValidationCriteria(IamcDataFilter)** with the new attribute, and **DataValidationCriteriaValue** and **DataValidationCriteriaBounds** inherit from that.
- If the validation fails and the warning-level is not None, add the value to a warning-list in
    https://github.com/IAMconsortium/nomenclature/blob/3a76cba2f5baf6c7f54be9d45d40c1a698738f6c/nomenclature/processor/data_validator.py#L96

    instead of the error-list.
- If the warning-list is not empty, display the warning-list as a DataFrame (after the error-list, but before raising the error).

Does that make sense, @phackstock?

**Comment by dc-almeida** [comment]
Clarification:
> display the warning-list as a DataFrame
Any example of how this would look?
And from what I understand, the fallback is always on raising the error if no warning level is specified.

**Comment by danielhuppmann** [comment]
> Any example of how this would look?

I'd say as a first step, take the same as 

https://github.com/IAMconsortium/nomenclature/blob/3a76cba2f5baf6c7f54be9d45d40c1a698738f6c/tests/test_validate_data.py#L108

but add a "warning-level" column.

> And from what I understand, the fallback is always on raising the error if no warning level is specified.

Correct.
