### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by phackstock** [IAMconsortium/nomenclature#47]
As discussed in #45 we should improve the error handling in `nomenclature/validation.py:validate`.

Currently we report a generic error and all the information about the invalid values is only given in the logging.
The advantage of this pattern is that we run through all validation steps so in a single go we get the complete picture of **all** invalid values. If we were to throw individual errors we would only get them one by one.
Therefore, any solution should keep this pattern where we collect all errors and only raise a single one at the end of the validation.
Inspiration can be taken from pydantic where all errors are collected and then handed over to an error handler `ValidationError`. `ValidationError` is an error itself that acts as a container class for all individual errors.

**Comment by danielhuppmann** [comment]
I guess that this can be closed? Or are there specific instances where this is still an issue?

**Comment by phackstock** [comment]
Ah yes I forgot to link the issue in the PR, this can be closed. If there's any more issues that I've overlooked I'll just open a new issue.
