### ISSUE TITLE
Start proper docs

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#53]
Set up a proper Sphinx-docs structure with the following sections:

- Overview and scope (pointing to openENTRANCE as the first use case, referencing pyam as the main dependency, with openENTRANCE and Horizon 2020 ackowledgement as in the current README)
- Usage (focus on the yaml format)
  - Code lists (region, variable with units, tags, generic)
  - Region mappings
- API documentation
- CLI documentation

**Comment by danielhuppmann** [comment]
- @LauWien, could you take a first pass with setting up the Sphinx structure (using the same layout as pyam), and then take care of setting this up on ReadTheDocs?
- @phackstock, could you add the content of the usage?

**Comment by LauWien** [comment]
>     * setting this up on ReadTheDocs?

Does IAMconsortium has an own RTD account so I can set it up? Right now I think I can only set up a documentation for RTD for all IIASA repositories and my own repositories, but not for this package.
