### ISSUE TITLE
Clean up API docs

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#78]
There are three issues in the API docs:

 - The intersphinx mapping to `nomenclature.RegionProcessor` currently does not work because the API docs are built with automodule, see the comment by @phackstock: https://github.com/IAMconsortium/nomenclature/pull/77#issuecomment-994814351
 - The auto-docs of the pydantic-based classes show a lot of functions that are not relevant to the users
 - Having the type-hints in the function signature makes for pretty-much-useless docs, see below (from [here](https://nomenclature-iamc.readthedocs.io/en/latest/api.html#nomenclature.process))
<img width="690" alt="image" src="https://user-images.githubusercontent.com/16931589/146200746-060c9912-2fee-4a40-b666-ab31f0a04f36.png">

**Comment by phackstock** [comment]
I guess I'll take this one after #76 is completed.
Comments from my side on the three points (in order):
* Should be easy to fix
* Should I only include `process`, `DataStructureDefinition` and `RegionProcessor`? 
* I'll take a look to see if there's an option for sphinx to exclude those from the docs. I agree it makes it really hard to read but for development I like to have them in the code. I'm sure we're not the first ones to encounter that issue and there's got to be a fix for it.

**Comment by phackstock** [comment]
Found the solution for the third point https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints
In `conf.py`:

```python
autodoc_typehints = "description" # or none
```
With the difference between 'description' and 'none' being that if there are no type hints in the doc string 'description' will add them while 'none' will not do anything.

**Comment by danielhuppmann** [comment]
> Should I only include process, DataStructureDefinition and RegionProcessor?

I'd also add `CodeList` and `RegionAggregationMapping`. My comment was aimed at functions like `update_forward_refs()` or the different `parse_*()` methods - at the current stage where each class has only two or three relevant methods, it would be preferably to list them explicitly rather than using auto-docs...
