### ISSUE TITLE
Double-check package config

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#80]
When installing the package (editable) in a new conda environment, I see the following in the list of installed packages:

```
nomenclature       0.1.dev14+g7aa3adf
nomenclature-iamc  0.2.dev15+gef3a1ec.d20211217 c:\users\huppmann\github\nomenclature
```

Seems like something is incorrect with setup.cfg?

**Comment by LauWien** [comment]
I guess it might be this [line](https://github.com/IAMconsortium/nomenclature/blob/main/setup.cfg#L12), which should say `packages = nomenclature-iamc` since it's published on PyPi with that name.

**Comment by phackstock** [comment]
As far as I understand `packages` simply tells setuptools what folders to install. 
If you compare pyam's setup.cfg https://github.com/IAMconsortium/pyam/blob/main/setup.cfg there's the same setup with packages = pyam and name = pyam-iamc.
So I don't think that's the culprit.

**Comment by phackstock** [comment]
I just looked at the commit hashes, the first one is from July 6th. The second one is the one before the currently latest.
Could this be an older install on your system?
I think the way virtualenv works is that it looks for packages not only in the virtual environment but also systemwide. It's just that the ones in the virtual environment take priority. Not sure how it is for conda environments though.
Is there a way to see when the install happened?

**Comment by danielhuppmann** [comment]
Uninstalling conda...

**Comment by danielhuppmann** [comment]
So even after re-installing conda from scratch, I get the following in the list of installed packages...
```
nomenclature        0.2.dev15+gef3a1ec.d20211217
nomenclature-iamc   0.2.dev16+g27ec9dc.d20211217 c:\users\huppmann\github\nomenclature
```

And I think I have identified the culprit:
- `nomenclature-iamc` refers to the installed **nomenclature** package (installed editable pointing to the GitHub clone)
- `nomenclature` refers to the installed CLI (located in the Scripts-folder of the conda environment, not the Lib)

So I think the "duplication" makes sense...

PS: also, I now finally have a cleaned-up conda installation on my machine...
