### ISSUE TITLE
Refactor tags to f-string style

### ISSUE THREAD

**Issue by danielhuppmann** [IAMconsortium/nomenclature#88]
The current use of `<Tag>` could be changed to `{Tag}` to be closer to Python f-string formatting.

Given that there are currently only two or three repositories using tags, this should be a manageable task to implement the change and update the repos simultaneously.

Thoughts @phackstock?

**Comment by phackstock** [comment]
I like the idea.
While not everyone might be familiar with python f-strings it might be a good learning opportunity.
Additionally, for people familiar with languages such as html or xml it might remove potential for confusion as `<tag>` has a different meaning there. While  as far as I'm aware curly brackets do not have any special meaning.
